[book]
authors = ["Diego Kingston", "Federico Carrone"]
language = "en"
multilingual = false
src = "src"
title = "Cryptography in Rust for Hackers"
[output.html]
mathjax-support = true
default-theme = "rust"
